name: 🚀 Deploy ECS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - libs/cli/**

jobs:
  deploy-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: Build
        run: |
          cd libs/ecs
          yarn build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
