name: ⚙️ Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - runs: yarn
      - name: Test Libs > CLI
        run: |
          cd libs/cli
          yarn lint
      - name: Test Libs > ECS
        run: |
          cd lib/ecs
          yarn lint
          yarn test
      - name: Test Libs > Core
        run: |
          cd libs/core
          yarn lint
