name: ⚙️ CLI Tests

on:
  push:
    branches: [ develop ]
    paths:
      - libs/cli/**
  pull_request:
    branches: [ develop ]
    paths:
      - libs/cli/**

jobs:
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn
      - name: Test Libs > CLI
        run: |
          cd libs/cli
          yarn lint