name: ⚙️ Tests

on:
  push:
    branches: [ develop ]
    paths:
      - libs/core/**
  pull_request:
    branches: [ develop ]
    paths:
      - libs/core/**

  test-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn
      - name: Test Libs > Core
        run: |
          cd libs/core
          yarn lint
