name: 🚀 Publish NPM

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Which package ?
        options: 
          - ecs
          - cli
      version:
        type: string
        description: Version to publish ?
        required: true

jobs:
  public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: Build & Publish ${{ github.event.inputs.name }}@${{ github.event.inputs.version }}
        run: |
          yarn turbo run build --filter=${{ github.event.inputs.name }}
          cd libs/${{ github.event.inputs.name }}
          npm version ${{ github.event.inputs.version }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
