name: 🚀 Publish NPM

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Which package to publish
        options: 
          - ecs
          - core
          - cli
      version:
        type: string
        description: version you want to publish
        required: true

jobs:
  deploy-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: Build & Publish
        run: |
          cd libs/${{ github.event.inputs.name }}
          yarn build
          npm version ${{ github.event.inputs.version }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
